github.com:
    users:
        CraftedByCode:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: CraftedByCode
